FROM python:3.10-slim

WORKDIR /app

# 加速 + 升级 pip
RUN pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/ \
    && pip install --no-cache-dir --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY rag_agent ./rag_agent

EXPOSE 8080

CMD ["uvicorn", "rag_agent.main:app", "--host", "0.0.0.0", "--port", "8080"]